### ISSUE TITLE
Consider paid products for inclusion

### ISSUE THREAD

**Issue by terrehbyte** [terrehbyte/awesome-ue4#3]
There are various paid products for UE4 that are worth considering acquiring a license for. One example of such is [Coherent GT,](http://coherent-labs.com/coherent-gt/) an HTML5-driven UI framework.

The spirit of this awesome list is to maintain a list of free and well-maintained resources, which is why paid assets were initially excluded. It's important to call attention to paid assets in order to create a more comprehensive list of resources. Paid teams do have the advantage of (hopefully) being able to create a better maintained product that is better supported via e-mail or forums or what-have-you.

## Tasks
- [ ] Gather paid products (in this issue tracker)
- [ ] Integrate them into the awesome list
- [ ] Clearly designate paid products as such
